import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils";
import Header from "@/components/Header";
import ScrollToTop from "@/components/custom/ScrollToTop";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('bg-primary', inter.className)}
      >
        <Header />
        {children}
        <Toaster />
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
